---
- hosts: 10.5.235.157
  gather_facts: False
  su: yes
  su_user: guest
  tasks:
  - name: update apt
    action: shell apt-get update
    tags:
    - build

  - name: install required software defined networking packages
    action: apt pkg=$item state=installed
    with_items:
      - openvswitch-datapath-source
      - bridge-utils
      - module-assistant
      - openvswitch-brcompat
      - openvswitch-common
      - openvswitch-switch
      - git
      - python-zdaemon
      - kvm
      - wget
      - dnsmasq
    tags:
    - build

  - name: install linux linux-headers
    action: shell apt-get install -y linux-headers-$(uname -r)
    ignore_errors: True
    tags:
    - build

  - name: check if the openvswitch-switch module is already built and installed
    action: shell lsmod | grep openvswitch_mod > /dev/null; echo $?
    ignore_errors: True
    register: openvswitch_module_installed
    tags:
    - build

  - name: build openvswitch-switch module
    action: shell module-assistant -t -q auto-install openvswitch-datapath
    when: '${openvswitch_module_installed} > 0'
    tags:
    - build

  - name: reboot
    action: command reboot
    when: '${openvswitch_module_installed} > 0'
    tags:
    - reboot

  - name: wait for the server to come back up after a reboot
    action: pause seconds=60
    when: '${openvswitch_module_installed} > 0'
    tags:
    - reboot

