---
- hosts: 10.5.235.157
  remote_user: guest
  sudo: yes
  tasks:
  - name: install openvswitch-switch
    apt: name=openvswitch-switch 
    tags:
    - install_ovs

  - name: config ovs to add br1
    shell: ovs-vsctl add-br br1
    tags:
    - config_ovs

  - name: config ovs to set br1 protocols
    shell: ovs-vsctl set bridge br1 protocols=OpenFlow13
    tags:
    - config_ovs

  - name: config ovs to add br1 address
    shell: ifconfig br1 192.168.1.2 netmask 255.255.255.0
    tags:
    - config_ovs

  - name: config ovs to add eth1
    shell: ovs-vsctl add-port br1 eth1
    tags:
    - config_ovs

  - name: config ovs to add controller
    shell: ovs-vsctl set-controller br1 tcp:192.168.1.1
    tags:
    - config_ovs


